[package]
name = "rbrain-search"
version.workspace = true
edition.workspace = true

[dependencies]
rbrain-core = { workspace = true }
tantivy = { workspace = true }
lindera-tantivy = { workspace = true }
lindera = { workspace = true }
lancedb = { workspace = true }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
arrow-buffer = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
text-splitter = { workspace = true }
ferrous-opencc = { workspace = true }

[lints]
workspace = true
